# AKGI - Crash into numpy - Part I
Bei *numpy* und *scipy* handelt es sich um Module von Python, welche sehr hilfreiche Funktionen für uns zur Verfügung stellen. In diesem Tutorial soll zunächst um Numpy gehen.

<center>
    <img src="img/horror.png" width="500">
*Bildquelle: http://www.zoitz.com/archives/36*
</center>


# numpy: Mathematische Kalkulationen in Python

*numpy* ist eine Bibliothek, die Python optimierte Vektoren, Matrizen und höher dimensionale Strukturen hinzufügt. Die Optimierung bezieht sich vor allem auf die Berechnungszeit, da die Bibliothek in C und Fortran implementiert ist. *numpy* ermöglicht einen einfachen Umgang mit Vektoren- und Matrizenberechnungen. Die Vereinfachung geht so weit, dass viele Wissenschaftler mit Python arbeiten und wichtige Bibliotheken des Maschinellen Lernens durch Python verwendet werden können.

Um die Funktionalität nutzen zu können, müssen Sie die Bibliothek erst einmal laden. Beim Importieren des Moduls hat sich die Konversion durchgesetzt *np* als Alias zu verwenden.

In [1]:
import numpy as np

## numpy arrays
Eine Kernfunktionalität von *numpy* besteht in den Datentyp *ndarray*. Stellen Sie sich diesen Datentypen als einen n-dimensionalle Array vor, wie Sie Ihn beispielsweise aus Java kennen. Durch diesen Datentyp lassen sich Skalare, Vektoren und Matrizen abbilden.

Es existieren unterschiedliche Möglichkeit einen _ndarray_ zu erzeugen. So können Sie beispielsweise:

* Listen oder Tupel zu einem *ndarray* machen, 
* die *numpy* Funktionen zum Erzeugen von *ndarray*-Strukturen verwenden, wie `arange`, `linspace`, `zeros` etc.
* oder Daten aus einer Datei in einen *ndarray* einlesen.

### Aus einer Liste erzeugen

In [2]:
# create a list
list = [1,2,3,4,5,6,7,8,9]

# create a numpy array from the list - it has the shape of a vector
vec = np.array(list)
print(vec, type(vec))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
# create a nested list
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

# create a numpy array from the list of lists - it has the shape of a matrix
mat = np.array(list_of_lists) 
print(mat, type(mat))




# create weird nested list
weird_list = [[1,2,3],[9,8,7],[3,4,6],[6,7,8,9]]
matw = np.array(weird_list)
print(matw, type(matw)) # keine Matrixformatierung mehr, wenn dien Listen nicht gleichlang sind!

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[1, 2, 3] [9, 8, 7] [3, 4, 6] [6, 7, 8, 9]] <class 'numpy.ndarray'>


Wie die Beispiele zeigen, unterscheiden sich die Variablen nicht in Ihrem Datentyp, sondern ausschließlich in Ihrer Form. Die Form eines *ndarray* können Sie durch das Attribut *shape* erfragen.

In [4]:
# shape property of a ndarrray
print(vec.shape) # vector shape
print(mat.shape) # matix shape
print(matw.shape) # wie ein Vektor

# but numpy has a shape function as well
print(np.shape(vec))
print(np.shape(mat))
print(np.shape(mat) == mat.shape)

(9,)
(3, 3)
(4,)
(9,)
(3, 3)
True


Sehr hilfreich kann auch das Attribute *size* sein.

In [5]:
# size property of a ndarray
print (vec.size)
print (mat.size)

9
9


Erzeugt man die Datenstruktur Arrays aus einer Liste, scheint kein besonderer Unterschied zwischen diesen zu bestehen. Hier ist jedoch zu beachten, dass die Python Liste ein **dynamischer Datentyp** ist und der Arrays nicht. Der **Datentyp des Arrays** wird beim **initialisieren festgelegt** und ist somit **statisch**. Dies hilft unter anderem bei der **Speichereffizienz** und der **Kalkulationsgeschwindigkeit** von Funktionen auf dem Datentyp. 

Mit `dtype` kann man diese Eigenschaft bei der Initialisierung setzen. Generell sind alle gängigen Typen zulässig, beispieslweise `int, float, complex, bool, object`, etc.; die Bitanzahl lässt sich bei bestimmten Datentypen ebenfalls setzen, wie bei `int16` oder `int64`.

In [6]:
# check the typ of data with dtype property
print (vec, vec.dtype)

# force the typ of the data with dtype
float_vec = np.array(list, dtype=complex) 
print (float_vec, float_vec.dtype)

[1 2 3 4 5 6 7 8 9] int32
[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j] complex128


### *numpy*-Funktion zum Erzeugen

Es exisiteren diverse Funktionen, um einen Array mit Inhalt zu füllen. Zum generieren von Intervallen, deren Abstände gleichmäßig verteilt sind, sind die Funktionen `arange` und `linspace` geeignet. `arange` benutzt einen gegebenen Abstandwert,  um innerhalb von gegebenen Intervallgrenzen entsprechende Werte zu generieren, während `linspace` eine bestimmte Anzahl von Werten innerhalb gegebener Intervallgrenzen berechnet. Den Abstand berechnet `linspace` automatisch.

** arange **

In [8]:
# arguments of arange are: arange(start, stop, step) -> Start ist mit drin, Stop ist nicht mit drin
# only stop argument, arange will start from 0 
print(np.arange(10))

# here are some other examples 
# with start and stop argument
print(np.arange(1, 10))
# with start, stop and step argument
print(np.arange(2, 10, 0.5))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.
  9.5]


**linespace**

In [171]:
# arguments of linespace are: linspace(start, stop, num=50, endpoint=True, retstep=False) 

# only with start and stop argument, linespace will create 50 values with even distance
print(np.linspace(0,98))

# set restep to true to get a tupel with ([ndarray],distance)
print(np.linspace(0,98,retstep=True))

# with start, stop and num argument, will create 10 values even distributed
print(np.linspace(0,98,10,retstep=True))

# same with an open interval --> distance = (stop-start)/num
print(np.linspace(0,98,10,endpoint=False,retstep=True)) # 9.8
print(np.linspace(0,98,20,endpoint=False,retstep=True)) # 4.9

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.
  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.  86.  88.
  90.  92.  94.  96.  98.]
(array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98.]), 2.0)
(array([  0.        ,  10.88888889,  21.77777778,  32.66666667,
        43.55555556,  54.44444444,  65.33333333,  76.22222222,
        87.11111111,  98.        ]), 10.88888888888889)
(array([  0. ,   9.8,  19.6,  29.4,  39.2,  49. ,  58.8,  68.6,  78.4,  88.2]), 9.8)
(array([  0. ,   4.9,   9.8,  14.7,  19.6,  24.5,  29.4,  34.3,  39.2,
        44.1,  49. ,  53.9,  58.8,  63.7,  68.6,  73.5,  78.4, 

Diese Funktionen erzeugen jedoch immer einen Array in Form eines Vektors. Die `shape` entspricht also immer (Anzahl,). Mit Hilfe der Funktion `reshape` können wir den erzeugten Array unseren Wünschen anpassen.

In [9]:
# create a vector of 25 values
vec = np.arange(25)
print(vec,vec.shape)

# reshape the vector to a 5x5 matrix - that only works if the dimesions fit
m_5x5 = vec.reshape(5,5)
print(m_5x5, m_5x5.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] (25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] (5, 5)


#### Weitere Funktion zum Generieren von Matrizen

In [10]:
# matrix of zeros - [lines,columns]
print(np.zeros([3, 2]))
print("-----------------------------")
print(np.zeros([2, 3]))
print("-----------------------------")
# matrix of ones - [lines,columns]
print(np.ones([3,3]))
print("-----------------------------")
# matrix of a constant - [lines,cloumns], constant
print(np.full([3,3], 0.33))
print("-----------------------------")
# diagonal matrix with diagonal of the given array and the shape of (len(array),len(array))
print(np.diag([1,3,2]))
print("-----------------------------")
# diagonal matrix with offset k from the main diagonal -> shape of (len(array)+k,len(array)+k)
print(np.diag([1,2,3], k=2)) 
print("-----------------------------")
# random.rand(lines,columns) gives you uniform random numbers between [0,1]
print(np.random.rand(4,4))
print("-----------------------------")
# random.randn(rows,columns) gives you standard normal distributed random numbers in the given shape
print(np.random.randn(4,4))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
-----------------------------
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
-----------------------------
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
-----------------------------
[[ 0.33  0.33  0.33]
 [ 0.33  0.33  0.33]
 [ 0.33  0.33  0.33]]
-----------------------------
[[1 0 0]
 [0 3 0]
 [0 0 2]]
-----------------------------
[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]
-----------------------------
[[ 0.96026381  0.32608181  0.83022144  0.99639752]
 [ 0.51960107  0.04058446  0.12018156  0.93955316]
 [ 0.33528408  0.39890279  0.56232171  0.67735017]
 [ 0.56447165  0.01156402  0.1152398   0.35050954]]
-----------------------------
[[ 1.16463394 -0.36027252 -0.79372203  0.95499861]
 [-0.25972128  0.29546262 -0.95126945 -0.34931722]
 [ 3.0204523   0.31849504  1.51774289  0.73465829]
 [-1.41115778 -0.61468204  0.8236077  -1.73215258]]


### Aus einer CSV-Datei lesen
### [AUFGABE IM CODE-TEIL]
*numpy* stellt ebenfalls die Möglichkeit zur Verfügung eine Matrix aus einer CSV-Datei zu erstellen. Hier wird die Funktion *genfromtxt* verwendet. Als kleines Beispiel ist hier die Durchschnittstemperatur von Berlin aus dem Jahr 2016 für die Monate Januar bis Dezember verwendet worden. Im weiteren Verlauf werden Sie diese Weise andere Dateien einlesen und für die weitere Analyse vorbereiten. Da es unter Umständen schwieriger werden kann, insbesondere wenn unterschiedliche Datentypen vorhanden sind, sollten Sie sich hierzu die [Dokumentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) angucken oder merken.

In [24]:
# read data from a csv file with genfromtxt
temp_berlin = np.genfromtxt('temp_berlin_2016.csv', delimiter=",")
print(temp_berlin,temp_berlin.shape)

# hinzufügen
temp_berlin = np.append(temp_berlin, [12,1.0])
temp_berlin = temp_berlin.reshape(12,2)

print(temp_berlin,temp_berlin.shape)

# rausdrücken
np.savetxt('temp_berlin_2016.csv', temp_berlin, fmt='%2.1f', delimiter=",")

# with savetxt you can write a ndarray into a csv file
# AUFAGBE: Modifizieren Sie temp_berlin, sodass es einen fiktiven Dezember gibt mit einer Druchschnittstemperatur
# und schrieben Sie die modifizierte temp_berlin-Variable in die CSV-Datei zurück

[[  1.    0.1]
 [  2.    4.2]
 [  3.    5.2]
 [  4.    9.4]
 [  5.   16.2]
 [  6.   19.7]
 [  7.   20.6]
 [  8.   19.1]
 [  9.   18.6]
 [ 10.    9.1]
 [ 11.    5.7]] (11, 2)
[[  1.    0.1]
 [  2.    4.2]
 [  3.    5.2]
 [  4.    9.4]
 [  5.   16.2]
 [  6.   19.7]
 [  7.   20.6]
 [  8.   19.1]
 [  9.   18.6]
 [ 10.    9.1]
 [ 11.    5.7]
 [ 12.    1. ]] (12, 2)


### Numpy Array referenzen und nicht kopieren

Mit Hilfe von _np.array_ wird eine Kopie anglegt. Handelt es sich bei dem Parameter schon um einen ndarray und Sie möchten nicht, dass eine Kopie angelegt wird, kann die Funktion _np.asarray_ verwendet werden.

In [25]:
# create a matrix 3x3
ones = np.ones([3,3])

# create a copy of that same matrix
copy_ones = np.array(ones)  

# only reference the matrix
ref_ones = np.asarray(ones)

# change a value and have a look
ones[1,1] = 44
print(ones)
print("-----------------------------")
print(copy_ones)
print("-----------------------------")
print(ref_ones)

[[  1.   1.   1.]
 [  1.  44.   1.]
 [  1.   1.   1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  1.   1.   1.]
 [  1.  44.   1.]
 [  1.   1.   1.]]


## Attribute eines Numpy Arrays

Mit Hilfe von dem Attribut `ndim` kann die Dimension eines `ndarrays` festgestellt werden. Die Dimension von *numpy* beschreibt die Dimension des Arrays, nicht die Dimension einer Matrix! So haben Arrays, welche Scalare repräsentieren die Dimension 0, Vektoren die Dimension 1 und Matrizen mindestens die Dimension 2.

In [27]:
# create some arrays
scalar = np.array(1)
vector = np.arange(25)
matrix = np.arange(25).reshape(5,5)

# print their dimension
print(scalar,scalar.ndim)
print("-----------------------------")
print(vector,vector.ndim)
print("-----------------------------")
print(matrix,matrix.ndim)

1 0
-----------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 1
-----------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 2


Einige weitere Attribute sind bereits vorgekommen dazu wählen `shape` (dieses entspricht der mathematischen Dimension) und `size`. Trotzdem seien Sie in der folgenden Liste noch einmal mit aufgeführt:

* `shape`: Die mathematische Dimension eines Array: n-mal-m Matrize, wobei m den Spalten entspricht und n den Zeilen
* `size`: Anzahl der Elemente im Array
* `itemsize`: Bytegröße eines Elements
* `nbytes`: Anzahl verwendeter Bytes
* `T`: Transponiert eine Matrix

In [77]:
# vector shape, count of the elements in the vector
print(vector.shape,vector.size)  

# bytes of an element, total bytes used by the vector (size*itemsize)
print(vector.itemsize,vector.nbytes)  

# transpose a matrix
print(matrix.T)

(25,) 25
8 200
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


## Manipulieren von Numpy Arrays

### Indexierungen - Zugriffmöglichkeiten

Die Zugriffsmöglichkeiten auf ein `ndarray` unterscheiden sich nicht stark gegenüber den Zugriffsmöglichkeiten, die Sie bereits von den Python Listen kennen. Es gibt einige kleine zusätzliche Optionen, welche Ihnen vielleicht bereits aus anderen Programmiersprachen bekannt sind, die Arrays verwenden.

In [29]:
# create a test vector and matrix
indexMatrix = np.arange(15).reshape(3,5)
print(indexMatrix,indexMatrix.shape) # let's have a look

# you can select a single value with matrix[row,column] - counting starts at 0
print(indexMatrix[0,2])

# you can select a full row
print(indexMatrix[0])     # use rowindex only
print(indexMatrix[0,:])   # use rowindex and slice operator, more clear

# you can also select columns
print(indexMatrix[:,1])   # use the slice operator to manipulate the row and select the column by an index

# you can change a single value
indexMatrix[0,2] = 44     # replace '2' with '44' at index [0,2]

# even replace whole rows or columns 
indexMatrix[1,:] = -11     # replace each value in row 1 with '-11'
indexMatrix[:,4] = 13      # replace each value in column 4 with '13'

print(indexMatrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
2
[0 1 2 3 4]
[0 1 2 3 4]
[ 1  6 11]
[[  0   1  44   3  13]
 [-11 -11 -11 -11  13]
 [ 10  11  12  13  13]]


### Index slicing
Index Slicing ist bereits von den Listen bekannt und bei Arrays etwas erweitert. Als Syntax können Sie sich merken `Matrize[von:bis:Schritt]` um anteilig aus dem Array herauszuschneiden.

In [30]:
# create a matrix for slicing
sliceMatrix = np.arange(25).reshape(5,5)
print(sliceMatrix)

print(sliceMatrix[:,1]) # cut a column, same like above
print(sliceMatrix[1:3,1]) # or cut only a part of that column
print(sliceMatrix[1::2,:]) # take only odd rows 
print(sliceMatrix[:,-1]) # using a negative index is also possible

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  6 11 16 21]
[ 6 11]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[ 4  9 14 19 24]


### [AUFGABE]
Mit dem gelernten sollten Sie die folgende Aufagbe lösen können. Erstellen Sie eine Matrize, welche die Werte von 1 bis 50 enthält un die Dimension 7 mal 7 hat. Basierend auf dieser Matrize erstellen Sie bitte weitere Matrizen, die den gelb markierten Bereichen entsprechen, durch Indexierung und Slicing:

<center>
    <img src="img/Aufgabe1.jpg" width="900">
</center>

<center>
    <img src="img/Aufgabe2.jpg" width="900">
</center>

In [106]:
# create a matrix with values from 1-50 with the dimension 7 by 7

# solution 1
# ...
# solution 10: Tipp: https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html


### Indexierungen mal anders
Indexierungen auf Numpy Arrays kann man auch durch Listen realisieren. So wird es möglich, dezidiert einzelne Werte herauszufiltern und in einer neuem neuen Array zu verpacken. Das selbe kann man durch eine boolche Maske erreichen. Beides soll hier kurz skizziert werden, da es sehr nützlich sein kann.

In [69]:
# get something to manipulate, again
fancyMatrix = np.arange(25).reshape(5,5)
print(sliceMatrix)

# create some arbitrary row and column indices
row_indices, column_indices = [0,2,3,4],[1,3,0,-2]
print(sliceMatrix[row_indices,column_indices]) # select values with indices [0,1], [2,3], [3,0], [4,3]

# look at it again, cause it can be pretty confusing!

# lets create a bool mask by hand
bool_mask = np.array([True,False,True,True,False])
print(sliceMatrix[1,bool_mask])

# or that a bit simpler
bool_mask_simpler = np.array([1,0,1,1,0], dtype=bool)
print(sliceMatrix[1,bool_mask_simpler]) # same result

# to get er more complex, you can do fancy stuff like:
bool_mask_generated = (5 < fancyMatrix) * (fancyMatrix % 2 == 0)
print(bool_mask_generated)
print(sliceMatrix[bool_mask_generated])

# also, look at it again!

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1 13 15 23]
[5 7 8]
[5 7 8]
[[False False False False False]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 6  8 10 12 14 16 18 20 22 24]


### Funktionen zum Manipulieren von Arrays
#### where function
Wennn Sie sich eine Maske erstellt haben, können Sie mit der `where` Funktion sich die Indizes ableiten lassen.

In [86]:
get_indices = np.where(bool_mask_generated)

print(get_indices)

(array([1, 1, 2, 2, 2, 3, 3, 4, 4, 4]), array([1, 3, 0, 2, 4, 1, 3, 0, 2, 4]))


#### flatten function
Eine Darstellung in Matrix-Form ist nicht immer wünschenswerte. Es wird passieren, dass Sie eine Matrix in eine Vektorrepäsentation überführen müssen. Dieses können Sie mit der bereits bekannten Funktion`reshape` erreichen. Allerdings ist es dafür notwendig die Dimensionen zu kennen. Eine einfach Variante ist `flatten`:

In [91]:
# some matrix in the shape of 10 by 3 
someMatrix = np.arange(30).reshape(10,3)
# flatten the matrix
print(someMatrix.flatten())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


#### diag function
Die Diagonale eine Matrix erhält man durch die `diag` Funktion, welche die Matrix und eventuell ein *offset* übergeben bekommt. Alternativ kann man die Funktion `diagonal`direkt auf dem Array aufrufen. 

In [67]:
# some matrix again in the shape of 5 by 5 and random numbers
someMatrix = np.random.rand(25).reshape(5,5)
print(someMatrix)
print("----------------------------------------------------------")
# use of diag
print(np.diag(someMatrix))
print("----------------------------------------------------------")
print(np.diag(someMatrix, 2))   # with an offset of 2
print("----------------------------------------------------------")
# call the function on the object itself
print(someMatrix.diagonal())
print("----------------------------------------------------------")
print(someMatrix.diagonal(-2))  # with an offset -2

[[ 0.48693375  0.37915977  0.5070796   0.82408141  0.70865803]
 [ 0.68945273  0.36724498  0.72940075  0.90485394  0.19960026]
 [ 0.31016     0.40484917  0.72582227  0.57000276  0.78244099]
 [ 0.52560615  0.61489971  0.22049464  0.4410948   0.73234121]
 [ 0.57919094  0.76108393  0.3774021   0.82113682  0.61736836]]
----------------------------------------------------------
[ 0.48693375  0.36724498  0.72582227  0.4410948   0.61736836]
----------------------------------------------------------
[ 0.5070796   0.90485394  0.78244099]
----------------------------------------------------------
[ 0.48693375  0.36724498  0.72582227  0.4410948   0.61736836]
----------------------------------------------------------
[ 0.31016     0.61489971  0.3774021 ]


## [AUFGABE]
Implementieren Sie eine Funktion `customDiag`, welche die Funktionalität der eben vorgestellten Funktion realisiert.

In [68]:
# create a funtion customDiag

def customDiag(matratze, offset=0): # Standardwert für Offset ist 0
    
    # hier noch ne Validerung der Eingabe machen
    
    listee=[] # das wird die Diagonale
    
    i = 0
    while i < matratze[0].size: # wir beginnen bei [0][0], also links oben inne Ecke
        try:
            if offset < 0:
                value = matratze[i+abs(offset)][i] # wir fangen +offset weiter unten an und gehen schräg runter
            else:
                value = matratze[i][i+offset] # wir fangen +offset weiter rechts an und gehen schräg runter

            # wenn wir hier ankommen, muss value ein gültiger Wert für die Diagonale sein
            listee.append(value) # also hinzufügen
            
        except IndexError: # wir sind irgendwie rausgekommen aus den Dimensionen der Matratze
            pass           # ist aber nicht weiter schlimm, einfach weiter machen
        i+=1
    
    return np.array(listee) # als numpy array zurückgeben

# make this work
testMatrix = np.ones([4,4])
print(customDiag(testMatrix))
print(customDiag(testMatrix,1))
print(customDiag(testMatrix,3))
print(customDiag(testMatrix,-1))
print(customDiag(testMatrix,-3))

[ 1.  1.  1.  1.]
[ 1.  1.  1.]
[ 1.]
[ 1.  1.  1.]
[ 1.]


## [AUFGABE]
Zur Wiederholung, lege Sie bitte jeweils eine Matrix(4x4) über die Möglichkeiten: Liste, arange, linespace, random.rand, random.randn, full und  zero an. Erinnern Sie sich an die Unterschiede und Limitation einzelner Varianten.

In [ ]:
# a lot of matrixes


## Numpys Dateiformat
Numpy hat ein eigenes Dateiformat, welche es ermöglicht die `ndarrays` zu speichern und wieder einzulesen. Hierfür werden die Funktionen `numpy.save` und `numpy.load` benutzt:

In [31]:
saveThis = np.random.randn(5,5)          # create a random matrix
np.save("zufallsmatrix.npy", saveThis)   # save the matrix to a numpy file

loadThis = np.load("zufallsmatrix.npy")  # load the stored matrix
print(loadThis, loadThis.shape)

[[ 0.41984026 -0.53678337  0.96354383  0.59926202 -0.40695817]
 [-1.96472731  1.2627941   1.06488224  0.93543625  0.64938886]
 [ 0.87075706  0.23015312 -1.03645035 -0.59434889 -0.42816931]
 [ 1.65385103  0.77093609 -0.22492213  0.9793807  -0.37237774]
 [ 0.8536109   0.20714373  0.40160166  0.21934984  0.27599389]] (5, 5)
